name: aws-codeartifact-token
description: generate aws codeartifact authorization token
inputs:
  codeartifact-domain:
    description: "https://<domain>-<domain-owner>.d.codeartifact.<region>.amazonaws.com/"
    required: true
  aws-role-oid:
    description: "the web identity role to assume to connect to aws"
    required: true
  aws-role-codeartifact:
    description: "the codeartifact role to assume after logging into aws (role-chain)"
    required: true

outputs:
  AWS_CODEARTIFACT_TOKEN:
    value: ${{ steps.generate.outputs.AWS_CODEARTIFACT_TOKEN }}

runs:
  using: composite
  steps:
    - name: extract information
      shell: bash
      id: info
      run: |
        url="${{ inputs.codeartifact-domain }}"

        u=${url#https://}; u=${u#http://}
        host=${u%%/*}; path=${u#*/}

        sub=${host%%.d.codeartifact.*}
        region=${host#*.d.codeartifact.}; region=${region%%.*}
        domain=${sub%-*}; domain_owner=${sub##*-}

        echo "domain=$domain" >> $GITHUB_OUTPUT
        echo "domain_owner=$domain_owner" >> $GITHUB_OUTPUT
        echo "region=$region" >> $GITHUB_OUTPUT

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws-role-oid }}
        aws-region: ${{ steps.info.outputs.region }}

    - name: assume codeartifact role
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws-role-codeartifact }}
        role-chaining: true
        aws-region: ${{ steps.info.outputs.region }}

    - name: generate codeartifact token
      id: generate
      shell: bash
      run: |
        echo "AWS_CODEARTIFACT_TOKEN=$(aws codeartifact get-authorization-token --domain ${{ steps.info.outputs.domain }} --domain-owner ${{ steps.info.outputs.domain_owner }} --query authorizationToken --output text)" >> $GITHUB_OUTPUT

