name: clean
description: clean github workspace
runs:
  using: composite
  steps:
  - name: list files
    shell: bash
    run: ls -a

  - name: clean
    shell: bash
    run: |
      echo "cleaning up working directory..."
      sudo rm -rf ./* ./.[!.]*
      ls -a
