name: build and push image

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
      tag-prefix:
        type: string
        default: ""
        description: "if you want to make a distro variant e.g. for alpine do 'alpine-'"
      context:
        type: string
        description: "the docker context to use relative to the git context"
        default: "."
      dockerfile:
        type: string
        description: "the dockerfile to use relative to the git context (default {context}/Dockerfile)"
        required: false
      target:
        type: string
        description: "the target within the dockerfile to build"
        required: false
      platforms:
        type: string
        description: "comma separated list of platforms compatible with qemu"
        default: linux/arm64
      push:
        type: boolean
        description: "whether to push the images or not (mainly used for testing)"
        default: true
      disable-latest:
        type: boolean
        description: "force exclude the latest tag"
        default: false
      ghcr:
        type: boolean
        description: "enable pushing to ghcr.io"
        default: true
      ghcr-image-name:
        type: string
        description: "override ghcr image name (default: repository name)"
        required: false
      ecr-repository:
        type: string
        description: "<account-id>.dkr.ecr.<region>.amazonaws.com/<image>"
        required: false
      aws-role-oid:
        type: string
        description: "the web identity role used to authenticate to aws"
        required: false
      aws-role-ecr:
        type: string
        description: "the role assumed after authenticating to get access to ecr"
        required: false

env:
  REGISTRY_NAME: ghcr.io/tracefy/${{ inputs.ghcr-image-name || github.event.repository.name }}
  DIGESTS_DIRECTORY: ./${{ github.sha }}/digests

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  prepare:
    runs-on: [self-hosted]
    outputs:
      platforms: ${{ steps.vars.outputs.platforms }}
    steps:
      - name: set variables
        id: vars
        env:
          PLATFORMS: ${{ inputs.platforms }}
        run: |
          data=$(echo "\"${PLATFORMS}\"" | jq -c 'split(",") | map({ "name": ., "runner": (if . == "linux/amd64" then "X64" else "ARM64" end)})')
          echo "platforms=${data}" >> $GITHUB_OUTPUT


  # https://docs.docker.com/build/ci/github-actions/multi-platform/#distribute-build-across-multiple-runners
  # modified to also use appropiate runner depending on architecture/platform
  # if no runner exists that for the platform, then it defaults to using qemu on a arm64 runner
  build:
    runs-on: [self-hosted, "${{ matrix.platform.runner }}"]
    needs: prepare
    strategy:
      fail-fast: false
      matrix:
        platform: ${{ fromJson(needs.prepare.outputs.platforms) }}
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: set temporary docker config
        run: |
          mkdir -p "$PWD/${{ github.run_id }}/.docker"
          echo "DOCKER_CONFIG=$PWD/${{ github.run_id }}/.docker" >> $GITHUB_ENV

      # - name: setup qemu
      #   uses: docker/setup-qemu-action@v3
      #   with:
      #     cache-image: false

      - name: setup buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: login to ecr
        if: ${{ inputs.ecr-repository != '' }}
        uses: tracefy/github-actions-workflows/.github/actions/aws-ecr-login@v2
        with:
          repository: ${{ inputs.ecr-repository }}
          aws-role-oid: ${{ inputs.aws-role-oid }}
          aws-role-ecr: ${{ inputs.aws-role-ecr }}

      - name: set variables
        id: vars
        env:
          ECR_NAME: ${{ inputs.ecr-repository }}
        run: |
          echo "artifact=digests-$(echo '${{ matrix.platform.name }}' | tr '/' '-')" >> $GITHUB_OUTPUT
          if [[ "$ECR_NAME" != "" && "${{ inputs.ghcr }}" == "true" ]]; then
            echo "names=\"name=${ECR_NAME},${REGISTRY_NAME}\"" >> $GITHUB_OUTPUT
          elif [[ "$ECR_NAME" != "" ]]; then
            echo "names=name=${ECR_NAME}" >> $GITHUB_OUTPUT
          else
            echo "names=name=${REGISTRY_NAME}" >> $GITHUB_OUTPUT
          fi


      - name: docker metadata
        id: meta
        uses: docker/metadata-action@v5
        env:
          ECR_NAME: ${{ inputs.ecr-repository != '' && inputs.ecr-repository || 'localhost:5000/dummy' }}
        with:
          images: |
            name=${{ env.REGISTRY_NAME }},enable=${{ inputs.ghcr }}
            name=${{ env.ECR_NAME }},enable=${{ inputs.ecr-repository != '' }}

      - name: build image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile == '' && format('{0}/Dockerfile', inputs.context) || inputs.dockerfile }}
          builder: ${{ steps.buildx.outputs.name }}
          platforms: ${{ matrix.platform.name }}
          labels: ${{ steps.meta.outputs.labels }}
          target: ${{ inputs.target }}
          outputs: type=image,${{ steps.vars.outputs.names }},push_by_digest=${{ inputs.push }},name-canonical=true,push=${{ inputs.push }}

      - name: export digests
        run: |
          mkdir -p "${DIGESTS_DIRECTORY}"
          digest='${{ steps.build.outputs.digest }}'
          touch "${DIGESTS_DIRECTORY}/${digest#sha256:}"

      # not possible to use output with matrix in this case
      # https://github.com/orgs/community/discussions/26639
      - name: upload digest
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.vars.outputs.artifact }}
          path: ${{ env.DIGESTS_DIRECTORY }}/*
          if-no-files-found: error
          retention-days: 1

  push:
    runs-on: self-hosted
    if: ${{ inputs.push }}
    needs: build
    steps:
      - name: download digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ env.DIGESTS_DIRECTORY }}
          pattern: digests-*
          merge-multiple: true

      - name: set temporary docker config
        run: |
          mkdir -p "$PWD/${{ github.run_id }}/.docker"
          echo "DOCKER_CONFIG=$PWD/${{ github.run_id }}/.docker" >> $GITHUB_ENV

      - name: setup buildx
        uses: docker/setup-buildx-action@v3

      - name: login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: login to ecr
        if: ${{ inputs.ecr-repository != '' }}
        uses: tracefy/github-actions-workflows/.github/actions/aws-ecr-login@v2
        with:
          repository: ${{ inputs.ecr-repository }}
          aws-role-oid: ${{ inputs.aws-role-oid }}
          aws-role-ecr: ${{ inputs.aws-role-ecr }}

      - name: docker metadata
        id: meta
        uses: docker/metadata-action@v5
        env:
          ECR_NAME: ${{ inputs.ecr-repository != '' && inputs.ecr-repository || 'localhost:5000/dummy' }}
        with:
          images: |
            name=${{ env.REGISTRY_NAME }},enable=${{ inputs.ghcr }}
            name=${{ env.ECR_NAME }},enable=${{ inputs.ecr-repository != '' }}
          tags: |
            type=raw,value=latest,prefix=${{inputs.tag-prefix}},enable=${{ inputs.disable-latest == false }}
            type=raw,value=${{ inputs.tag }},prefix=${{inputs.tag-prefix}},enable=${{ !contains(inputs.tag, '.') }}
            type=semver,pattern={{version}},value=${{ inputs.tag }},prefix=${{inputs.tag-prefix}},enable=${{ contains(inputs.tag, '.') }}
            type=semver,pattern={{major}},value=${{ inputs.tag }},prefix=${{inputs.tag-prefix}},enable=${{ contains(inputs.tag, '.') }}
            type=semver,pattern={{major}}.{{minor}},value=${{ inputs.tag }},prefix=${{inputs.tag-prefix}},enable=${{ contains(inputs.tag, '.') }}
            type=sha,enable=true,prefix=${{inputs.tag-prefix}},suffix=,format=short
            type=sha,format=short,prefix=${{inputs.tag-prefix}}{{branch}}-,suffix=-{{date 'YYYYMMDDHHmmss'}},event=push,priority=1

      - name: create manifest list and push to ghcr
        if: ${{ inputs.ghcr }}
        working-directory: ${{ env.DIGESTS_DIRECTORY }}
        run: |
          docker buildx imagetools create $(jq --arg name "$REGISTRY_NAME" -cr '.tags | unique | map(select(startswith($name))) | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.REGISTRY_NAME }}@sha256:%s ' *)

      - name: create manifest list and push to ecr
        if: ${{ inputs.ecr-repository != '' }}
        working-directory: ${{ env.DIGESTS_DIRECTORY }}
        run: |
          docker buildx imagetools create $(jq --arg name "$REGISTRY_NAME" -cr '.tags | unique | map(select(startswith($name) | not)) | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ inputs.ecr-repository }}@sha256:%s ' *)

      - name: inspect ghcr image
        if: ${{ inputs.ghcr }}
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY_NAME }}:${{ steps.meta.outputs.version }}

      - name: inspect ecr image
        if: ${{ inputs.ecr-repository != '' }}
        env:
          ECR_NAME: ${{ inputs.ecr-repository }}
        run: |
          docker buildx imagetools inspect "$ECR_NAME:${{ steps.meta.outputs.version }}"
