name: Deploy

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      service:
        required: false
        type: string
        default: ${{ github.event.repository.name }}
    secrets:
      t:
        description: 'A token passed from the caller workflow'
        required: true
      host:
        description: 'A token passed from the caller workflow'
        required: true
      ssh_private_key:
        description: 'A token passed from the caller workflow'
        required: true
      registry:
        description: 'A token passed from the caller workflow'
        required: true
      u:
        description: 'A token passed from the caller workflow'
        required: true
env:
  SSH_AUTH_SOCK: /tmp/${{ github.event.repository.name }}ssh_agent.sock
jobs:
  clean:
    uses: tracefy/github-actions-workflows/.github/workflows/utilities-clean.yml@master

  deploy:
    needs:
      - clean
    runs-on: [ self-hosted ]
    steps:
      - name: Login to register AWS
        run: |
          ssh ${{ secrets.host }} 'sudo /usr/local/bin/aws ecr get-login-password --region eu-central-1 | sudo docker login --username AWS --password-stdin ${{ secrets.REGISTRY }}'

      - name: Login to registry GitLab
        run: ssh ${{ secrets.host }} 'echo ${{ secrets.GITLAB_DEPLOY_TOKEN }} | sudo docker login registry.gitlab.com -u docker --password-stdin'

      - name: Github docker login
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: ssh ${{ secrets.host }} 'sudo su -c "echo ${{ secrets.t }} | docker login ghcr.io -u ${{ secrets.u }} --password-stdin"'

      - name: Deploy container
        run: ssh ${{ secrets.host }} 'sudo docker service update --image=${{ secrets.registry }}/${{ github.event.repository.name }}:${{ inputs.tag }} --with-registry-auth --force --detach=false --update-parallelism=1 --update-delay=2s --update-failure-action=rollback --update-order=start-first default_${{ inputs.service }}'
