name: build and push image

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      platforms:
        type: string
        default: linux/arm64
      push:
        type: bool
        default: true
    secrets:
      token:
        description: The GITHUB_TOKEN used for authenticating to ghcr.io
        required: true

jobs:
  build:
    runs-on: [self-hosted, ARM64]
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup qemu
        if: ${{ contains(inputs.platforms, ",") || !contains(inputs.platforms, "linux/arm64") }}
        uses: docker/setup-qemu-action@v3

      - name: setup buildx
        uses: docker/setup-buildx-action@v3

      - name: login to container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.token }}

      - name: docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/tracefy/${{ github.event.repository.name }}
          tags: |
            type=raw,value=${{ inputs.tag }},enable=${{ !contains(inputs.tags, ".") }}
            type=semver,pattern={{version}},value=${{ inputs.tag }},enable=${{ contains(inputs.tags, ".") }}
            type=semver,pattern={{major}},value=${{ inputs.tag }},enable=${{ contains(inputs.tags, ".") && !(startsWith(inputs.tags, "0.") || startsWith(inputs.tags, "v0.")) }}
            type=semver,pattern={{major}}.{{minor}},value=${{ inputs.tag }},enable=${{ contains(inputs.tags, ".") && !(startsWith(inputs.tags, "0.") || startsWith(inputs.tags, "v0.")) }}
            type=sha,enable=true,prefix=,suffix=,format=short

      - name: build and push
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ inputs.platforms }}
          push: ${{ inputs.push }}
          load: ${{ !inputs.push }}
          tags: ${{ steps.meta.outputs.tags }}

      - name: list docker images
        run: docker image ls

      - name: ./.github/actions/clean.yml
        if: always()
