name: Deploy

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      service:
        required: false
        type: string
        default: ${{ github.event.repository.name }}
env:
  SSH_AUTH_SOCK: /tmp/${{ github.event.repository.name }}ssh_agent.sock
jobs:
  clean:
    uses: tracefy/github-actions-workflows/.github/workflows/utilities-clean.yml@master

  deploy:
    needs:
      - clean
    runs-on: [ self-hosted ]
    steps:
      - name: Login to registery AWS
        run: |
          echo "$HOST"
          ssh ${{ inputs.host }} 'sudo /usr/local/bin/aws ecr get-login-password --region eu-central-1 | sudo docker login --username AWS --password-stdin ${{ secrets.REGISTRY }}'

      - name: Login to registry GitLab
        run: ssh ${{ inputs.host }} 'echo ${{ secrets.GITLAB_DEPLOY_TOKEN }} | sudo docker login registry.gitlab.com -u docker --password-stdin'

      - name: Github docker login
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: ssh ${{ inputs.host }} 'sudo su -c "echo ${{ secrets.GH_PA_TOKEN }} | docker login ghcr.io -u ${{ secrets.GH_PA_USER }} --password-stdin"'

      - name: Deploy container
        run: ssh ${{ inputs.host }} 'sudo docker service update --image=${{ secrets.registry }}/${{ github.event.repository.name }}:${{ inputs.tag }} --with-registry-auth --force --detach=false --update-parallelism=1 --update-delay=2s --update-failure-action=rollback --update-order=start-first default_${{ inputs.service }}'
