name: Deploy with jumphost

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      service:
        required: false
        type: string
        default: ${{ github.event.repository.name }}
    secrets:
      host:
        description: 'some description'
        required: true
      jump_host:
        description: 'some description'
        required: true
      registry:
        description: 'some description'
        required: true
      GH_PA_TOKEN:
        description: 'some description'
        required: true
      GH_PA_USER:
        description: 'some description'
        required: true
env:
  SSH_AUTH_SOCK: /tmp/${{ github.event.repository.name }}/ssh_agent.sock
jobs:
  clean:
    uses: tracefy/github-actions-workflows/.github/workflows/utilities-clean.yml@master

  deploy:
    needs:
      - clean
    runs-on: [ self-hosted ]
    steps:
      - name: Tag version
        run: echo "${{ inputs.tag }}"
      - name: Github docker login
        run: ssh -A -J ${{ secrets.jump_host }} ${{ secrets.host }} 'sudo su -c "echo ${{ secrets.GH_PA_TOKEN }} | docker login ghcr.io -u ${{ secrets.GH_PA_USER }} --password-stdin"'
      - name: Deploy container
        run:  ssh -A -J ${{ secrets.jump_host }} ${{ secrets.host }} 'sudo docker service update --image=ghcr.io/tracefy/${{ github.event.repository.name }}:${{ inputs.tag }} --with-registry-auth --force --detach=false --update-parallelism=1 --update-delay=2s --update-failure-action=rollback --update-order=start-first default_${{ inputs.service }}'
