name: CI Test

on:
  workflow_call:

jobs:
  clean:
    uses: tracefy/github-actions-workflows/.github/workflows/utilities-clean.yml@master
  test:
    runs-on: ubuntu-latest
    needs:
      - clean
    services:
      mariadb:
        image: mariadb:10.5
        env:
          MYSQL_DATABASE: api
          MYSQL_USER: mariadb
          MYSQL_PASSWORD: mariadb
          MYSQL_ROOT_PASSWORD: mariadb
        ports:
          - 3306

      dynamodb:
        image: amazon/dynamodb-local:latest
        ports:
          - 8000

    steps:
      - uses: actions/checkout@v3
#      - name: Log in to the packages registery.
#        run: |
#          echo $CR_PAT | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Test
        env:
          AWS_ENDPOINT: http://127.0.0.1:${{job.services.dynamodb.ports[8000]}}
          DB_CONNECTION: mariadb:mariadb@tcp(127.0.0.1:${{job.services.mariadb.ports[3306]}})/api
        run: go clean --testcache && go test -v ./...
