name: CI Test

on:
  workflow_call:

jobs:
  clean:
    uses: tracefy/github-actions-workflows/.github/workflows/utilities-clean.yml@master
  test:
    runs-on: ubuntu-latest
    needs:
      - clean
    services:
      mariadb:
        image: mariadb:10.5
        env:
          MYSQL_DATABASE: api
          MYSQL_USER: mariadb
          MYSQL_PASSWORD: mariadb
          MYSQL_ROOT_PASSWORD: mariadb
        ports:
          - 3306
    steps:
      - uses: actions/checkout@v3
      - name: Log in to the Container registry
        run: |
          echo ${{ secrets.GH_PA_TOKEN }} | docker login ghcr.io -u ${{ secrets.GH_PA_USER }}  --password-stdin
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Test
        env:
          DB_CONNECTION: mariadb:mariadb@tcp(127.0.0.1:${{job.services.mariadb.ports[3306]}})/api
        run: go clean --testcache && go test -v ./...
