name: CI test

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string

jobs:
  tests:
    runs-on: [ self-hosted ]
    strategy:
      matrix:
        node-version: [ inputs.node-version ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name : Compile app
        run: |
          npm ci
          npm run test