name: Publish npm package

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string

jobs:
  publish:
    runs-on: [ self-hosted ]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          registry-url: https://npm.pkg.github.com/
          username: ${{ secrets.GH_PA_USER }}
          password: ${{ secrets.GH_PA_TOKEN }}
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm run build
      - run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GH_PA_TOKEN}}