name: normalize php

on:
  workflow_call:

jobs:
  clean:
    uses: tracefy/github-actions-workflows/.github/workflows/utilities-clean.yml@master
  normalize:
    container:
      image: ghcr.io/tracefy/master-disk-php:alpine-latest
    needs:
      - clean
    runs-on: [ self-hosted ]
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          ${{ secrets.PACKAGIST_SET_CONFIG}}
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: normalize php
        run: php vendor/bin/phpcbf
      - uses: stefanzweifel/git-auto-commit-action@v4.15.1
        with:
          commit_message: Fix formatting with phpcbf
