name: Psalm

on:
  workflow_call:

jobs:
  clean:
    uses: tracefy/github-actions-workflows/.github/workflows/utilities-clean.yml@master
  psalm:
    container:
      image: ghcr.io/tracefy/master-disk-php:alpine-latest
    needs:
      - clean
    name: psalm
    runs-on: [ self-hosted ]
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          ${{ secrets.PACKAGIST_SET_CONFIG}}
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Run psalm
        run: ./vendor/bin/psalm

