name: normalize composer.json

on:
  workflow_call:

jobs:
  clean:
    uses: tracefy/github-actions-workflows/.github/workflows/utilities-clean.yml@master
  normalize:
    needs:
      - clean
    runs-on: [ self-hosted ]
    container:
      image: ghcr.io/tracefy/php-ci-container:alpine-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: normalize composer.json
        run: |
          ${{ secrets.PACKAGIST_SET_CONFIG}}
          composer config --no-plugins allow-plugins.ergebnis/composer-normalize true
          composer require ergebnis/composer-normalize --ignore-platform-req=ext-intl
          composer normalize
      - uses: stefanzweifel/git-auto-commit-action@v4.15.1
        with:
          commit_message: normalize composer.json
