name: CI Test

on:
  workflow_call:

  pull_request:
    branches: [ "master" ]

jobs:
  clean:
    uses: tracefy/github-actions-workflows/.github/workflowsutilities-clean.yml@master
  laravel-tests:
    needs:
      - clean
    container: mariadb:10.5
    services:
      mysql:
        image: mariadb:10.5
        env:
          MYSQL_USER: mysql
          MYSQL_PASSWORD: mysql
          MYSQL_DATABASE: api
          MYSQL_ROOT_PASSWORD: mysql
        ports:
          - 3306:3306
    runs-on: [ self-hosted ]

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - uses: actions/checkout@v3
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: |
          ${{ secrets.PACKAGIST_SET_CONFIG}}
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --ignore-platform-reqs

      - name: Setup DB
        env:
          MYSQL_HOST: 127.0.0.1:${{ job.services.mysql.ports['3306'] }}
          MYSQL_USER: mysql
          MYSQL_PASSWORD: mysql
          MYSQL_DATABASE: api
          MYSQL_ROOT_PASSWORD: mysql
        run: php artisan migrate:fresh && php artisan seed

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: php artisan test
