name: CI Test

on:
  workflow_call:

jobs:
  build:
    services:
      mysql:
        image: mariadb:10.5
        env:
          MYSQL_USER: mysql
          MYSQL_PASSWORD: mysql
          MYSQL_DATABASE: api
          MYSQL_ROOT_PASSWORD: mysql
        ports:
          - 3306
    runs-on: [ self-hosted ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.7"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Setup config
        run: |
          [[ -e config_test.yml ]] && cp config_test.yml config.yml
      - name: Test with pytest
        run: |
          pytest

