name: python-test-uv

on:
  workflow_call:
    inputs:
      require_typecheck:
        type: boolean
        default: false
      test_coverage_configured_internally:
        type: boolean
        default: false

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: assert uv.lock is present
        shell: bash
        run: |
          # require uv.lock to be present in the repository
          [ -f uv.lock ] || (echo "uv.lock missing" 1>&2 && exit 1)

      - name: install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: set up python
        run: uv python install

      - name: install dependencies
        run: |
          uv sync --all-extras --dev --all-packages
          uv add --dev pytest pytest-cov coverage
          uv add --dev ruff
          uv add --dev basedpyright

      - name: format check
        run: uv run ruff format --check

      - name: lint
        run: uv run ruff check

      - name: typecheck
        continue-on-error: ${{ inputs.require_typecheck == false }}
        run: uv run basedpyright

      # https://docs.pytest.org/en/stable/reference/exit-codes.html
      - name: test
        shell: bash
        run: |
          if [[ "${{ inputs.test_coverage_configured_internally }}" == "true" ]]; then
            COV_OPTION="--cov"
          else
            COV_OPTION="--cov=src"
          fi

          uv run pytest $COV_OPTION --cov-report= --cov-branch || {
            exit_code=$?
            # allow exit code 0 (all pass) and 5 (no tests found)
            if [[ $exit_code -ne 0 && $exit_code -ne 5 ]]
            then
              exit $exit_code
            fi
            if [[ $exit_code -eq 5 ]]
            then
              rm .coverage
            fi
          }

      - name: coverage
        shell: bash
        run: |
          if [[ -f .coverage ]]
          then
            uv run coverage report
          fi
