name: Deploy
on:
  workflow_call:
jobs:
  build:
    runs-on: [ self-hosted ]
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run  export

      - name: Deploy
        uses: lbertenasco/s3-deploy@v1
        with:
          folder: _static
          bucket: tcf.follow.tracefy.acceptance
          dist-id: E5DJ6BSE0LE44
          invalidation: / *