name: Prepare
on:
  workflow_call:
outputs:
  branch: ${{ steps.vars.outputs.branch }}
  tag: ${{ steps.vars.outputs.tag }}
  sha_short: ${{ steps.vars.outputs.sha_short }}
runs-on: self-hosted
steps:
  - uses: actions/checkout@v3
  - name: Declare variables
    id: vars
    shell: bash
    run: |
      echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
      echo "tag=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
      echo "sha_short=git rev-parse --short HEAD" >> $GITHUB_OUTPUT